# Generated by Django 4.1.2 on 2022-10-11 13:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('num_pais', models.CharField(max_length=3)),
                ('num_ddd', models.CharField(max_length=3)),
                ('num_telefone', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('num_pais', models.CharField(max_length=3)),
                ('num_ddd', models.CharField(max_length=3)),
                ('num_telefone', models.CharField(max_length=15)),
                ('crm', models.CharField(max_length=15)),
                ('crm_UF', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=50)),
                ('areaAtuacao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
