# Generated by Django 4.1.2 on 2022-10-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telemed', '0002_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='link_consulta',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
