# Generated by Django 4.1.2 on 2022-10-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_telemed', '0004_alter_consulta_link_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='requisito',
        ),
    ]
