# Generated by Django 4.1.2 on 2022-10-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telemed', '0005_remove_consulta_requisito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_requisito',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
