# Generated by Django 4.1.2 on 2022-10-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telemed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_med', models.BigIntegerField()),
                ('id_cli', models.BigIntegerField()),
                ('requisito', models.IntegerField()),
                ('data_requisito', models.DateField(auto_now_add=True)),
                ('data_consulta', models.DateTimeField()),
                ('obs', models.CharField(max_length=150)),
                ('link_consulta', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('documento', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
